export const GET_DATA_ENERGY_PER_HOUR = 'app/DataEnergy/GET_DATA_ENERGY_PER_HOUR';
export const GET_DATA_ENERGY_PER_HOUR_SUCCESS = 'app/DataEnergy/GET_DATA_ENERGY_PER_HOUR_SUCCESS';
export const GET_DATA_ENERGY_PER_HOUR_FAIL = 'app/DataEnergy/GET_DATA_ENERGY_PER_HOUR_FAIL';

export const GET_DATA_ENERGY_PER_DAY = 'app/DataEnergy/GET_DATA_ENERGY_PER_DAY';
export const GET_DATA_ENERGY_PER_DAY_SUCCESS = 'app/DataEnergy/GET_DATA_ENERGY_PER_DAY_SUCCESS';
export const GET_DATA_ENERGY_PER_DAY_FAIL = 'app/DataEnergy/GET_DATA_ENERGY_PER_DAY_FAIL';

export const CHANGE_STORE_DATA = 'app/DataEnergy/CHANGE_STORE_DATA';
